export type CsvColumn<T> = {
  header: string;
  key: keyof T | string;
  serialize?: (row: T) => string;
};

export function exportToCsv<T extends Record<string, any>>(
  filename: string,
  rows: T[],
  columns: CsvColumn<T>[]
) {
  const escape = (v: unknown) => {
    const s = v == null ? "" : String(v);
    return s.includes(",") || s.includes('"') || s.includes("\n")
      ? `"${s.replace(/"/g, '""')}"`
      : s;
  };
  const header = columns.map((c) => escape(c.header)).join(",");
  const body = rows
    .map((row) =>
      columns
        .map((c) =>
          escape(c.serialize ? c.serialize(row) : row[c.key as keyof T])
        )
        .join(",")
    )
    .join("\n");
  const blob = new Blob([header + "\n" + body], { type: "text/csv;charset=utf-8;" });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename;
  a.click();
  URL.revokeObjectURL(url);
}

/** Downloads a branded XLSX template from the server for the given table key. */
export function downloadBrandedTemplate(tableKey: string) {
  const a = document.createElement("a");
  a.href = `/api/export/template/${tableKey}`;
  a.download = `distillr-${tableKey}-template.xlsx`;
  a.click();
}

export function parseCsv(text: string): Record<string, string>[] {
  const lines = text.replace(/\r\n/g, "\n").replace(/\r/g, "\n").trim().split("\n");
  if (lines.length < 2) return [];

  const parseRow = (line: string): string[] => {
    const cells: string[] = [];
    let cur = "";
    let inQuote = false;
    for (let i = 0; i < line.length; i++) {
      const ch = line[i];
      if (ch === '"') {
        if (inQuote && line[i + 1] === '"') { cur += '"'; i++; }
        else inQuote = !inQuote;
      } else if (ch === "," && !inQuote) {
        cells.push(cur.trim());
        cur = "";
      } else {
        cur += ch;
      }
    }
    cells.push(cur.trim());
    return cells;
  };

  const headers = parseRow(lines[0]);
  return lines.slice(1).filter((l) => l.trim()).map((line) => {
    const vals = parseRow(line);
    const obj: Record<string, string> = {};
    headers.forEach((h, i) => { obj[h] = vals[i] ?? ""; });
    return obj;
  });
}

/**
 * Parses a CSV or XLSX file into an array of row objects keyed by column header.
 * For XLSX files generated by our branded template, rows 1-2 are branding banners
 * and row 4 is a hints row — those are skipped automatically; row 3 is the header row.
 */
export async function parseImportFile(file: File): Promise<Record<string, string>[]> {
  if (file.name.toLowerCase().endsWith(".xlsx") || file.name.toLowerCase().endsWith(".xls")) {
    const XLSX = await import("xlsx");
    const buf = await file.arrayBuffer();
    const wb = XLSX.read(buf, { type: "array", raw: false, dateNF: "yyyy-mm-dd" });
    const ws = wb.Sheets[wb.SheetNames[0]];
    const raw = XLSX.utils.sheet_to_json<any[]>(ws, { header: 1, defval: "" });
    if (raw.length < 2) return [];
    // Detect branded template: row 0 is a single merged banner cell, row 2 has the actual headers
    // We check if row[0] has only 1 non-empty value (the branding banner)
    const firstRowFilled = (raw[0] as any[]).filter((c: any) => c !== "").length;
    let headerRowIdx = 0;
    if (firstRowFilled <= 1 && raw.length >= 3) {
      // branded template: row index 2 is the headers row (0-indexed)
      headerRowIdx = 2;
    }
    const headers = (raw[headerRowIdx] as any[]).map(String);
    return raw
      .slice(headerRowIdx + 1)
      .filter((r: any[]) => r.some((c: any) => c !== ""))
      // skip the hints row (row immediately after headers in branded template = row index 3)
      .filter((_r: any[], i: number) => !(headerRowIdx === 2 && i === 0))
      .map((r: any[]) => {
        const obj: Record<string, string> = {};
        headers.forEach((h, i) => { obj[h] = r[i] != null ? String(r[i]) : ""; });
        return obj;
      });
  }
  // Default: treat as CSV
  const text = await file.text();
  return parseCsv(text);
}
