[build]
  builder = "nixpacks"
  buildCommand = "npm run build"

[deploy]
  startCommand = "npm run start"
  healthcheckPath = "/api/auth/me"
  healthcheckTimeout = 100
  restartPolicyType = "on_failure"
  restartPolicyMaxRetries = 3
